# Site settings
title: Jajang Irawan | UI & UX Designer
email: izzi.bdg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Jajang Irawan. I am UI & UX Designer for more than 3 years. I love coffee and Teh Tarik. I think a design means a lot to so many other things. First, good design will satisfy client. Then, an excellent design makes user easier to navigate the site. Moreover, satisfied users will bring more benefit to that site’s owner. All in all, a design can lead to huge success in so many ways, if it's done well.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jajangirawan.com" # the base hostname & protocol for your site
twitter_username: jajang_irawan

# Build settings
markdown: kramdown
