# Site settings
title: Jajang Irawan | UI & UX Designer
email: izzi.bdg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jajangirawan.com" # the base hostname & protocol for your site
twitter_username: jajang_irawan

# Build settings
markdown: kramdown
